# Generated by Django 5.0.6 on 2024-07-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('name',), 'verbose_name': 'patient', 'verbose_name_plural': 'patients'},
        ),
    ]
