# Generated by Django 5.0.6 on 2024-07-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0004_delete_customer_delete_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('name',), 'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
    ]
