# Generated by Django 5.0.6 on 2024-07-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0006_rename_student_petitioner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petitioner',
            options={'ordering': ('name',), 'verbose_name': 'petitioner', 'verbose_name_plural': 'petitioners'},
        ),
        migrations.AddField(
            model_name='petitioner',
            name='nationality',
            field=models.CharField(default='0000000', max_length=20),
        ),
    ]
