# Generated by Django 5.0.6 on 2024-07-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0007_alter_petitioner_options_petitioner_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitioner',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
